name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Abs6187:$HF_TOKEN@huggingface.co/spaces/Abs6187/AgentX-Travel-India_v01 main || {
            echo "Retrying push after failure"
            sleep 5
            git push --force https://Abs6187:$HF_TOKEN@huggingface.co/spaces/Abs6187/AgentX-Travel-India_v01 main
          }
